openprinting-cups-filters: fix compile errors.
"qpdf_cm.cc:(.text+0x730): undefined reference to `QPDFObjectHandle::assertStream()'" It seems to missing linking qpdf,